Dev PR
alexeybs90/go_final_project pull request #1
Opened 2024-10-07 12:45 UTC by alexeybs90

2024-10-08 08:57 UTC, dirtymew requested changes
Привет Алексей

хорошая работа:
 - тесты проходят
 - добавлена документация
 - структура проекта


дал рекомендации что поправить и улучшить, в целом критичных замечаний не много, после их исправления готов принять проект

2024-10-08 08:57 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
лучше go mod download

2024-10-08 08:57 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go_final_project
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 это лучше в ENV

2024-10-08 08:57 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu:latest
тут рекомендую выбрать образ полегче - типа alpine

2024-10-08 08:57 UTC, dirtymew commented on Dockerfile
> +EXPOSE 8080
если TODO_PORT другой будет?

2024-10-08 08:57 UTC, dirtymew commented on Dockerfile
> +ENV TODO_PASSWORD=qwerty
с сикретами лучше так не работать

2024-10-08 08:57 UTC, dirtymew commented on README.md
> +# Итоговое задание go_final_project
отлично что дописал документацию

2024-10-08 08:57 UTC, dirtymew commented on handlers/functions.go
> +		pass := os.Getenv("TODO_PASSWORD")
тут стоит переделать - не нужно делать запросык к OS в хендлерах

это очень накладная операция

всю конфигурацию стоит на получить считать и потом использовать

2024-10-08 08:57 UTC, dirtymew commented on handlers/functions.go
> +	todayStr := time.Now().Format("20060102")
20060102 вынести в константу и везде использовать

2024-10-08 08:57 UTC, dirtymew commented on handlers/handlers.go
> +	res.Write([]byte(result))
_ , _ = w.Write()
тут стоит либо явно проигнорировать ошибку или ее логировать
хорошие линтеры на это ругаться будут и не зря

2024-10-08 08:57 UTC, dirtymew commented on handlers/handlers.go
> +	dbpass := os.Getenv("TODO_PASSWORD")
уже выше писал про syscall в хендлере - это стоит переделать

2024-10-08 08:57 UTC, dirtymew commented on main.go
> +	// d, _ := time.Parse("20060102", "20240925")
лишние комментарии стоит убрать

2024-10-08 08:57 UTC, dirtymew commented on handlers/handlers.go
> +		task, err := parseAndCheckTask(req)
тут получилось не очень оптимально

те на этот энпоинт ты делаешь 2 запроса к бд в итоге

кажется что одного бы хватило

2024-10-08 08:57 UTC, dirtymew commented on store/Task.go
> +func (t Task) CheckSave() error {
мб Validate?

2024-10-08 08:57 UTC, dirtymew commented on handlers/functions.go
> +	if req.Method == http.MethodPut {
очень странная функция получилось - советую отрефакторить 

и сделать может быть несколько на так чтобы они делали что-то одно...

2024-10-08 08:57 UTC, dirtymew commented on handlers/functions.go
> +		//проверим, есть ли такая таска в бд
не понятно зачем

2024-10-08 08:57 UTC, dirtymew commented on store/store.go
> +	if err != nil {
можно проверить RowsAffected - и вернуть ошибку если запрос не был применен ни к одной строке

2024-10-08 08:57 UTC, dirtymew commented on store/store.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-10-08 08:57 UTC, dirtymew commented on store/store.go
> +		sql.Named("limit", 30))
лимит лучше вынести в константу

2024-10-08 08:57 UTC, dirtymew commented on store/store.go
> +	if search != "" {
очень не очевидный код -  рекомендую не строить так запросы

тут проще написать 3 отдельных запросы и явные условия - тогда будет сразу понятно что происходит

2024-10-08 08:57 UTC, dirtymew commented on store/Task.go
> +package store
store/Task.go - файл назван неверно - task.go

2024-10-08 08:57 UTC, dirtymew commented on store/store.go
> +var DB Store
так конечно не стоит делать и Store нужно было передать зависимостью в хендлеры

по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage

2024-10-08 08:57 UTC, dirtymew commented on main.go
> +	err := http.ListenAndServe(":"+port, nil)
стоит вывести в консоль сообщение что сервис на таком-то порту запущен - это еше нужно чтобы понять что приложение стартовало корректно

2024-10-08 20:47 UTC, alexeybs90 commented on Dockerfile
> +ENV TODO_PASSWORD=qwerty
а как работать? это же условно-учебный проект, нас по другому не учили :)

2024-10-08 21:00 UTC, dirtymew commented on Dockerfile
> +ENV TODO_PASSWORD=qwerty
для учебного не важно скорее общая рекомендации

можно просто не использовать дефолты или не комитить их в git

2024-10-08 21:03 UTC, alexeybs90 commented on Dockerfile
> +ENV TODO_PASSWORD=qwerty
в условии задачи сказано, что пароль должен браться из переменной окружения TODO_PASSWORD.
Буду рад если скажете, как лучше и безопаснее

2024-10-08 21:03 UTC, dirtymew commented on Dockerfile
> +ENV TODO_PASSWORD=qwerty
а мб не понял вопрос

если ты про то как в докере - то вот например так https://docs.docker.com/compose/how-tos/use-secrets/

2024-10-08 21:06 UTC, dirtymew commented on Dockerfile
> +ENV TODO_PASSWORD=qwerty
> в условии задачи сказано, что пароль должен браться из переменной окружения TODO_PASSWORD. Буду рад если скажете, как лучше и безопаснее

просто вообще убрать ) так не будет просто дефолта...

2024-10-08 21:19 UTC, alexeybs90 commented on store/Task.go
> +package store
так там же вроде структура Task в этом файле и больше ничего, разве так не принято называть файлы точно так же, как и класс?

2024-10-08 21:21 UTC, dirtymew commented on store/Task.go
> +package store
с большой буквы не называют файлы go

2024-10-08 21:33 UTC, alexeybs90 commented on store/store.go
> +var DB Store
medium заблокирован в РФ :)
поищу задачу про посылки

2024-10-08 21:40 UTC, dirtymew commented on store/store.go
> +var DB Store
https://github.com/DoWithLogic/golang-clean-architecture

https://dev.to/remast/the-ddd-hamburger-for-go-2156

похожие статьи

2024-10-10 19:13 UTC, dirtymew approved these changes
Алексей

задание принимаю

поздравляю и желаю удачи

2024-10-10 19:13 UTC, dirtymew commented on Dockerfile
> +COPY --from=build /app/web /app/web
отделяй пустыми строками разные инструкции - для удобства чтения

2024-10-10 19:13 UTC, dirtymew commented on store/Task.go
> +package store
@alexeybs90 файл не переименовал - в go файлы только с маленькой буквы

```
Files

- Go follows a convention where source files are all lower case with underscore separating multiple words.
- Compound file names are separated with _
- File names that begin with “.” or “_” are ignored by the go tool
- Files with the suffix _test.go are only compiled and run by the go test tool.

```

https://stackoverflow.com/questions/25161774/what-are-conventions-for-filenames-in-go

https://go.dev/doc/effective_go#names

2024-10-10 19:13 UTC, dirtymew commented on handlers/handlers.go
> +	TodoPassword string
а зачем экспортируемое поле?

2024-10-10 19:13 UTC, dirtymew commented on handlers/handlers.go
> +func (s TaskService) SignIn(res http.ResponseWriter, req *http.Request) {
для авторизации лучше воспользоваться паттерном middleware

https://refactoring.guru/ru/design-patterns/chain-of-responsibility

2024-10-10 21:27 UTC, alexeybs90 commented on store/Task.go
> +package store
я переименовал, это в гит почему то не попало
![image](https://github.com/user-attachments/assets/df7b1b99-0cd5-44b0-a929-58b3ac1e2972)

2024-10-10 21:28 UTC, alexeybs90 commented on Dockerfile
> +COPY --from=build /app/web /app/web
Спасибо!

2024-10-10 21:30 UTC, alexeybs90 commented on handlers/handlers.go
> +	TodoPassword string
> а зачем экспортируемое поле?

в него пихается значение переменной окружения TODO_PASSWORD из main()

2024-10-10 21:52 UTC, alexeybs90 commented on handlers/handlers.go
> +func (s TaskService) SignIn(res http.ResponseWriter, req *http.Request) {
> для авторизации лучше воспользоваться паттерном middleware
> 
> https://refactoring.guru/ru/design-patterns/chain-of-responsibility

http.HandleFunc("/api/task/done", service.Auth(service.Done))

service.Auth это и есть middlware, который используется во многих методах по заданию и проверяет авторизацию по куке, но зачем в самом SignIn middlware? Что он должен делать?

2024-10-10 23:05 UTC, dirtymew commented on handlers/handlers.go
> +	TodoPassword string
это понятно - но зачем это поле экспортируемое?

2024-10-10 23:05 UTC, dirtymew commented on handlers/handlers.go
> +	TodoPassword string
передавай в конструкторе или через метод

2024-10-10 23:05 UTC, dirtymew commented on handlers/handlers.go
> +func (s TaskService) SignIn(res http.ResponseWriter, req *http.Request) {
да комментарии не тут написал - это отдельный эндоинт.

про Auth конечно - в целом идея таже

но грубо говоря через middleware должны все запросы проходить - а в ней уже решатся что делать с запросом 

например если это авторизация - то в миддлевар сама должна решить пропускать запрос или что-то проверять... 

не уверен что понятно объяснил...

2024-10-10 23:05 UTC, dirtymew commented on store/Task.go
> +package store
ммм мб у тебя такая проблема - https://stackoverflow.com/questions/10523849/how-do-you-change-the-capitalization-of-filenames-in-git

2024-10-11 08:27 UTC, alexeybs90 commented on store/Task.go
> +package store
> ммм мб у тебя такая проблема - https://stackoverflow.com/questions/10523849/how-do-you-change-the-capitalization-of-filenames-in-git

спасибо, помогло: git config --global core.ignorecase false
git config --local core.ignorecase false

2024-10-12 18:48 UTC, merged